package com.projetpi.cloudup.entities;

public enum categories {
    CIVIL_ENGINEERING,

    SOFTWARE_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    MATERIAL_SCIENCE,
    ELECTRONICS,
    ROBOTICS,
    EMBEDDED_SYSTEMS,
    RENEWABLE_ENERGY,
    ARTIFICIAL_INTELLIGENCE,
    STUDY_TIPS,
    UNIVERSITY_DETAILS,
    COURSE_DETAILS
}
